#!/bin/sh

# google closure compiler (for javascript)
wget http://closure-compiler.googlecode.com/files/compiler-latest.zip -O ./tmp.zip
unzip tmp.zip compiler.jar
rm tmp.zip

mv compiler.jar gcc.jar

# yui compressor (for css)
wget http://yuilibrary.com/downloads/yuicompressor/yuicompressor-2.4.2.zip -O ./tmp.zip
unzip -j tmp.zip yuicompressor-2.4.2/build/yuicompressor-2.4.2.jar
rm tmp.zip

mv yuicompressor-2.4.2.jar yui.jar
