#!/usr/bin/php
<?

// something like config
require dirname(dirname(__FILE__)) . '/defines.php';

// requiring helpers
require 'scheduler.php';

// initialize mongo connection
try {
	$mongo = new Mongo();
} catch (MongoConnectionException $e) {
	die("Can't connect to mongo db\n");
}

$dbname = DB;

$db = $mongo->$dbname;

// lets do it
$scheduler = new Scheduler($db);
$scheduler->processJobList();
