#!/usr/bin/php
<?php

// something like config
require dirname(dirname(__FILE__)) . '/defines.php';

// requiring helpers
require 'scheduler.php';

// initialize mongo connection
try {
	$mongo = new Mongo();
} catch (MongoConnectionException $e) {
	die("Can't connect to mongo db\n");
}

$dbname = DB;

$db = $mongo->$dbname;

// lets do it
$scheduler = new Scheduler($db);

$action = isset($argv[1]) ? $argv[1] : 'joblist';

$lockname = 'lock_' . $action . '.tmp';

if (file_exists($lockname))
	die();

touch($lockname);

if ('joblist' === $action) {
	$scheduler->processJobList();
} else
if ('queue' === $action) {
	$scheduler->processQueue();
}

unlink($lockname);
