#!/usr/bin/php
<?php

$action = isset($argv[1]) ? $argv[1] : 'joblist';

$lockname = '/tmp/lock_' . $action . '.tmp';

if (file_exists($lockname)) {
	$mtime = filemtime($lockname);

	if (time() - $mtime > 120) {
		$pid = file_get_contents($lockname);

		if ($pid) {
			echo 'Dropping old process ' . $pid . "\n";
			$cmd = 'kill ' . $pid;
			exec($cmd);
		}
	} else {
		die();
	}
}

file_put_contents($lockname, getmypid());

echo '[' . date('H:m:s') . "] =============================================\n";

require dirname(__DIR__) . DIRECTORY_SEPARATOR . 'bootstrap.php';

// lets do it
$scheduler = new Scheduler();

if ('joblist' === $action) {
	$scheduler->processJobList();
} else
if ('queue' === $action) {
       $scheduler->processQueue();
} else
if ('rss' === $action) {
	$scheduler->updateGlobalRSS();
}

unlink($lockname);
