#!/bin/bash

ZIPPATH=/tmp/ext
PWDPATH=${PWD}

if [ -d "${ZIPPATH}" ]; then
	rm -rf ${ZIPPATH}
fi

mkdir ${ZIPPATH}

echo 'rsync'
rsync -rupEogtz --exclude-from=../excludes/chromeapp ../../../extensions/chrome/app/ ${ZIPPATH}/ > /dev/null

cd ${ZIPPATH}

zip -9 -r ${PWDPATH}/app.zip ./

cd ${PWDPATH}

echo 'removing dir'
rm -rf ${ZIPPATH}
