#!/bin/bash

desc() {
        echo ''
        echo -e "\033[1m${1}...\033[0m"
}

dt=`date +%T`
desc "Lets begin (${dt})"

desc 'Removing temp folder contents'
rm -rf ./tmp/*

desc 'Preparing'
echo 'rsync'
rsync -rupEogtz --exclude-from=./excludes ../../ tmp/ > /dev/null

echo 'making folders and links'
mkdir tmp/public_html/js
mkdir tmp/public_html/css
ln -s /srv/bstorage/jobs tmp/public_html/jobs

# done with google api
#desc 'Compressing javascript'
#echo 'jQuery...'
#java -jar tmp/other/utils/compiler.jar --js ../../public_html/js/jquery.js --warning_level QUIET > tmp/public_html/js/jquery.js
#gzip -c9 tmp/public_html/js/jquery.js > tmp/public_html/js/jquery.js.gz

desc 'Compressing'
echo 'javascript...'
java -jar tmp/other/utils/compiler.jar --js ../../public_html/js/funcs.js --js ../../public_html/js/filter.js --js ../../public_html/js/lang.js --js ../../public_html/js/sites.js --js ../../public_html/js/categories.js --js ../../public_html/js/index.js --externs ../../public_html/js/jquery.js --compilation_level ADVANCED_OPTIMIZATIONS --warning_level QUIET > tmp/public_html/js/index.js
gzip -c9 tmp/public_html/js/index.js > tmp/public_html/js/index.js.gz

echo 'css'
java -jar tmp/other/utils/yui.jar --type css -o tmp/public_html/css/main.css ../../public_html/css/main.css
gzip -c9 tmp/public_html/css/main.css > tmp/public_html/css/main.css.gz

desc 'Modifications'
echo 'index page'
./indexprepare > tmp/public_html/index.html
gzip -c9 tmp/public_html/index.html > tmp/public_html/index.html.gz

echo 'debug in defines'
sed 's/DEBUG/UNDEBUG/' ../../defines.php > tmp/defines.php
echo 'nginx...'
sed "s/workbreeze.dev/workbreeze.com/;s/\/home\/silent\/Projects\/work/\/srv\//" ../../other/configs/nginx.conf > tmp/other/configs/nginx.conf

desc 'Making iso'
mkisofs -r -J -l -d -o breeze.iso tmp/
