#!/bin/bash

desc() {
        echo ''
        echo -e "\033[1m${1}...\033[0m"
}

dt=`date +%T`
desc "Lets begin (${dt})"

desc 'Removing temp folder contents'
rm -rf ./tmp/*

desc 'Syncing'
echo 'rsync'
rsync -rupEogtz --exclude-from=./excludes ../../ tmp/ > /dev/null

desc 'PHP stripper'
for File in `find tmp/ -name '*.php'`; do 
	echo ${File}

	php -w ${File} > ${File}.tmp

	mv ${File}.tmp ${File}
done

desc 'Links and folders'

mkdir tmp/public_html/js
mkdir tmp/public_html/css
ln -s /srv/bstorage/jobs tmp/public_html/jobs

desc 'Compressing'
echo 'preparing js...'
./jsprepare ../../public_html/js/storage.js    > tmp/1.js
./jsprepare ../../public_html/js/settings.js   > tmp/2.js 
./jsprepare ../../public_html/js/filter.js     > tmp/3.js
./jsprepare ../../public_html/js/lang.js       > tmp/4.js
./jsprepare ../../public_html/js/sites.js      > tmp/5.js
./jsprepare ../../public_html/js/categories.js > tmp/6.js
./jsprepare ../../public_html/js/ajax.js       > tmp/7.js
./jsprepare ../../public_html/js/index.js      > tmp/8.js

echo 'javascript...'
java -jar tmp/other/utils/compiler.jar --js tmp/1.js --js tmp/2.js --js tmp/3.js --js tmp/4.js --js tmp/5.js --js tmp/6.js --js tmp/7.js --js tmp/8.js --externs ../../public_html/js/jquery.js --compilation_level ADVANCED_OPTIMIZATIONS --warning_level QUIET > tmp/public_html/js/index.js
gzip -c9 tmp/public_html/js/index.js > tmp/public_html/js/index.js.gz

rm tmp/{1,2,3,4,5,6,7,8}.js

echo 'css...'
java -jar tmp/other/utils/yui.jar --type css -o tmp/public_html/css/main.css ../../public_html/css/main.css
gzip -c9 tmp/public_html/css/main.css > tmp/public_html/css/main.css.gz

desc 'Modifications'
echo 'index page'
./indexprepare > tmp/public_html/index.html
gzip -c9 tmp/public_html/index.html > tmp/public_html/index.html.gz

gzip -c9 tmp/public_html/favicon.ico > tmp/public_html/favicon.ico.gz

echo 'debug in defines'
sed 's/DEBUG/UNDEBUG/' ../../defines.php > tmp/defines.php
echo 'nginx...'
sed "s/workbreeze.dev/workbreeze.com/;s/\/home\/silent\/Projects\/work/\/srv\//" ../../other/configs/nginx.conf > tmp/other/configs/nginx.conf

desc 'Making iso'
mkisofs -r -J -l -d -o breeze.iso tmp/
