#!/bin/bash

desc() {
        echo ''
        echo -e "\033[1m${1}...\033[0m"
}

dt=`date +%T`
desc "Lets begin (${dt})"

desc 'Removing temp folder contents'
rm -rf ./tmp/*

desc 'Syncing'
echo 'rsync'
rsync -rupEogtz --exclude-from=./excludes ../../ tmp/ > /dev/null

desc 'PHP stripper'
for File in `find tmp/ -name '*.php'`; do 
	echo ${File}

	php -w ${File} > ${File}.tmp

	mv ${File}.tmp ${File}
done

desc 'Links and folders'

mkdir tmp/public_html/js
mkdir tmp/public_html/css

ln -s /srv/bstorage/rss-global.xml tmp/public_html/rss-global.xml
ln -s /srv/bstorage/rss-global.xml.gz tmp/public_html/rss-global.xml.gz

desc 'Preparing static pages'
./htmlprepare ../../public_html/index.html tmp/public_html/

gzip -c9 tmp/public_html/index.html > tmp/public_html/index.html.gz

gzip -c9 tmp/public_html/favicon.ico > tmp/public_html/favicon.ico.gz

echo 'debug in bootstrap'
sed 's/DEBUG/UNDEBUG/' ../../bootstrap.php > tmp/bootstrap.php
echo 'nginx...'
sed "s/workbreeze.dev/workbreeze.com/;s/\/home\/Projects\/work/\/srv\//" ../../other/configs/nginx.conf > tmp/other/configs/nginx.conf

desc 'Making iso'
mkisofs -r -J -l -d -o breeze.iso tmp/
