#!/usr/bin/php
<?php

require dirname(__DIR__) . DIRECTORY_SEPARATOR . 'bootstrap.php';

$mongo = new Mongo();

$dbname = DB;

$db = $mongo->$dbname;

function checkCI($db, $collection, $indexes = array()) {
	$c = $db->$collection;

	$c->deleteIndexes();

	foreach($indexes as $index) {
		echo 'Creating index on ' . $collection . ":\n";

		$params = array();

		if (isset($index['_params'])) {
			if ($index['_params'] == 'unique') {
				$params['unique'] = true;
			}

			unset($index['_params']);
		}

		foreach($index as $key => $sort) {
			echo '  ' . $key . ' => ' . $sort . "\n";
		}

		echo "\n";

		$c->ensureIndex($index, $params);
	}
}

checkCI($db, 'sites', array(
	array(
		'code' => 1,
		'_params' => 'unique'
	)
));

checkCI($db, 'jobs', array(
	array(
		'stamp' => 1,
		'_params' => 'unique'
	),
	array(
		'cats' => 1
	),
	array(
		'stem' => 1
	)
));

checkCI($db, 'queue', array(
	array(
		'rnd' => 1
	)
));

echo "Repairing...\n";

$db->repair();
