#!/usr/bin/php
<?php

require dirname(__DIR__) . DIRECTORY_SEPARATOR . 'bootstrap.php';

$j = Database::jobs();

$sphinx = mysqli_connect('127.0.0.1', '', '', '', 9306);

$c = $j->find();

while ($item = $c->getNext()) {
	print_r($item);
	continue;

	if (isset($item['stem'])) {
		unset($item['stem']);

		$j->remove(array('_id' => $item['_id']));

		$j->insert($item);

		echo '*';
	}

	$q = mysqli_query($sphinx, 'select * from jobs where stamp = ' . $item['stamp']);
	$rec = mysqli_fetch_assoc($q);

	if (count($rec) > 0) {
		echo '-';
		continue;
	}

	$sql = 'insert into jobs values (' . $item['stamp'] . ', \'' . mb_replace('\'', '\\\'', $item['title'] . ' ' . $item['desc']) . '\', ' .
		$item['site'] . ', \'' . (sizeof($item['cats']) > 0 ? implode(' ', $item['cats']) . ' ' : '') . '\')';

	if (!mysqli_query($sphinx, $sql)) {
		echo mysqli_error($sphinx);
	}

	echo '+';
}

echo "\n";
