#!/usr/bin/php
<?

require('defines.php');

class DBChecker {
	private $db;

	private $categories;

	public function __construct($db) {
		$this->db = $db;

		$this->categories = $this->db->cats;
	}
	
	public function checkCat($code, $alias = '') {
		$cat = array(
			'code'  => $code,
			'alias' => $alias
		);

		$catElement = $this->categories->findOne($cat);

		if (null === $catElement) {
			echo '[' . $alias . "] category not found...\n";

			$this->categories->insert($cat);
		}
	}
}

$mongo = new Mongo();

$dbname = DB;

$db = $mongo->$dbname;

$c = new DBChecker($db);

$c->checkCat(0, 'dev');
$c->checkCat(1, 'sysadm');
$c->checkCat(2, 'write');
$c->checkCat(3, 'manage');
$c->checkCat(4, 'design');
$c->checkCat(5, 'other');
