#!/usr/bin/php
<?php

require dirname(__DIR__) . DIRECTORY_SEPARATOR . 'bootstrap.php';

$mongo = new Mongo();

$dbname = DB;

$db = $mongo->$dbname;

$pc = $db->sites;

$parsers = glob(PATH_CLASSES . 'parsers' . DIRECTORY_SEPARATOR . '*.php');

foreach($parsers as $parser) {
	$pinfo = pathinfo($parser);
	
	$className = 'Parser_' . $pinfo['filename'];
	
	$parser = new $className($db);
	
	$info = array(
		'code' => $parser->getSiteCode()
	);
	
	$tmp = $pc->findOne($info);
	
	if (null != $tmp) {
		$pc->remove($info);
	}
	
	$info['class']  = $className;
	$info['folder'] = $parser->getSiteFolder();
	$info['name']   = $parser->getSiteName();
	$info['url']    = $parser->getUrl();
	$info['lang']   = $parser->getLang();
	$info['script'] = $pinfo['basename'];
	
	$pc->insert($info);
}

echo "Done\n";
