#!/usr/bin/php
<?php

// something like config
require('../defines.php');

// requiring helpers
require(PATH_CLASSES . 'scheduler.php');

// initialize mongo connection
try {
	$mongo = new Mongo();
} catch (MongoConnectionException $e) {
	die("Can't connect to mongo db\n");
}

$dbname = DB;

$db = $mongo->$dbname;

// lets do it
$scheduler = new Scheduler($db);

$action = isset($argv[1]) ? $argv[1] : 'joblist';

$lockname = '/tmp/lock_' . $action . '.tmp';

if (file_exists($lockname)) {
	$mtime = filemtime($lockname);

	if (time() - $mtime > 120) {
		$pid = file_get_contents($lockname);

		if ($pid) {
			echo 'Dropping old process ' . $pid . "\n";
			$cmd = 'kill ' . $pid;
			$tmp = system($cmd);
		}
	} else {
		die();
	}
}

file_put_contents($lockname, getmypid());

if ('joblist' === $action) {
	$scheduler->processJobList();
} else
if ('queue' === $action) {
       $scheduler->processQueue();
} else
if ('rss' === $action) {
	$scheduler->updateGlobalRSS();
}

unlink($lockname);
