#!/usr/bin/php
<?php

require('../defines.php');

$mongo = new Mongo();

$dbname = DB;

$db = $mongo->$dbname;

$jobs = $db->jobs;

// a week for jobs
$t = time() - 60 * 60 * 24 * 7;

$jc = $jobs->find(
	array('stamp' => array(
		'$lt' => $t
	))
);

$sfolders = array();

while ($job = $jc->getNext()) {
	if (!isset($sfolders[$job['site']])) {
		$tmp = $db->sites->findOne(
			array('code' => $job['site'])	
		);

		$sfolders[$tmp['code']] = $tmp['folder'];
	}
	
	$file = PATH_PUBLIC . 'jobs' . 
		DIRECTORY_SEPARATOR . $sfolders[$job['site']] .
		DIRECTORY_SEPARATOR . $job['id'] . '.html';
	$filegz = $file . '.gz';
	
	echo $file . "\n";
	echo $filegz . "\n";

	$jobs->remove(array(
		'_id' => $job['_id']
	));

	unlink($file);
	unlink($filegz);
}
