#!/usr/bin/php
<?php

require dirname(__DIR__) . DIRECTORY_SEPARATOR . 'bootstrap.php';

$jobs = Database::jobs();

// month for job offers
$t = time() - 60 * 60 * 24 * 30;

$jc = $jobs->find(
	array('stamp' => array(
		'$lt' => $t
	))
);

while ($job = $jc->getNext()) {
	echo '-';

	Sphinx::remove('jobs', $job['stamp']);

	$jobs->remove(array(
		'_id' => $job['_id']
	));
}
