#!/usr/bin/php
<?

require(dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . 'defines.php');
require(PATH_CLASSES . 'tester.php');

$mongo = new Mongo();

$dbname = DB;

$db = $mongo->$dbname;

Tester::testFolder($db, dirname(__FILE__) . DIRECTORY_SEPARATOR . 'tests' . DIRECTORY_SEPARATOR);
