#!/usr/bin/php
<?php

require dirname(dirname(__DIR__)) . DIRECTORY_SEPARATOR . 'www' . DIRECTORY_SEPARATOR . 'bootstrap.php';
require __DIR__ . DIRECTORY_SEPARATOR . 'compress.php';

$tmpdir = '/tmp/tmpjs/';

if (
	!isset($argc)
	|| $argc < 2
) {
	die("Source page modules dir required\n");
}

if ($argc < 3) {
	die("Path to store output modules required\n");
}

// source path

$sdir = realpath($argv[1]) . DS;

if (!file_exists($sdir)) {
	die($sdir . " - path not found\n");
}

// output path

$odir = realpath($argv[2]) . DS;

if (!file_exists($odir)) {
	die($odir . " - path not found\n");
}

// paths for compilers

$path_gcc = trim(`find ../ -name 'gcc.jar'`);
$path_yui = trim(`find ../ -name 'yui.jar'`);

// begin

foreach(glob($sdir . '*.php') as $filename) {
	$name = pathinfo($filename, PATHINFO_FILENAME);

	echo "\n== " . $name . ".php\n";

	$jsname = $name . '.js';
	$classname = 'M' . ucfirst($name);

	$module = new $classname();

	if (
		$module instanceof PageModule
		&& $scripts = $module->getJS()
	) {
		$js = '';
	
		foreach ($scripts as $script) {
			$js .= shell_exec('./jsprepare ' . escapeshellarg(PATH_PUBLIC . 'js' . DS . $script . '.js')) . "\n";
		}
		
		$tmpname = '/tmp/' . $jsname;
		
		file_put_contents($tmpname, $js);
		
		//$compressedJS = compressJS(array($tmpname), '');
		
		unlink($tmpname);
	}
		
	$c = file_get_contents($filename);
	
	if (preg_match('@getJS\(\) {(.*?)}@siu', $c, $matches)) {
		$c = str_replace($matches[1], 'return array(\'' . $jsname . '\');', $c);
	}

	if (false !== strpos($c, '#githash')) {
		$hash = trim(`git show --pretty=format:%H --quiet`);

		$c = str_replace('#githash', $hash, $c);
	}
	
	if (preg_match_all('@<<<EOF(.*?)EOF;@siu', $c, $matches)) {
		$m = array_pop($matches);
		
		foreach($m as $part) {
			$tmp = "\n" . PageModule::compress($part) . "\n";
			
			$c = str_replace($part, $tmp, $c);
		}
	}
	
	$tmpname = '/tmp/' . $name . '.php';
	
	file_put_contents($tmpname, $c);
	
	$content = shell_exec('php -w ' . escapeshellarg($tmpname));
	
	unlink($tmpname);
	
	file_put_contents($odir . $name . '.php', $content);
}

__halt_compiler();

// adding version to all css files
if (
	preg_match_all('@"(css/(.*?)\.css)"@iu', $content, $matches)
	&& 3 === sizeof($matches)
) {
	$files = $matches[1];

	foreach($files as $file) {
		$content = str_replace($file, $file . '?' . $dd, $content);

		echo str_pad($file, 40);

		$fileout = $outdir . $file;

		if (file_exists($fileout)) {
			echo "[exists]\n";
			continue;
		}

		if (!file_exists(dirname($fileout))) {
			mkdir(dirname($fileout));
		}

		echo "[compressing]\n";

		$filepath = PATH_PUBLIC . $file;
		
		$output = system('java -jar ' . escapeshellarg($path_yui) . 
				' --type css -o ' .	escapeshellarg($fileout) . ' ' .
			escapeshellarg($filepath));

		echo $output;
	}

	echo "\n";
}

if (
	preg_match_all('@<\!-- gcc(.*?)\/gcc \!-->@siu', $content, $matches)
	&& 2 === sizeof($matches)
) {
	$src = $matches[0];
	$blocks = $matches[1];

	$inc = -1;

	foreach($blocks as $bkey => $block) {
		if (
			preg_match_all('@"(js/(.*?)\.js)"@iu', $block, $matches)
			&& 3 === sizeof($matches)
		) {
			++$inc;

			$files = $matches[1];

			if (!file_exists($tmpdir)) {
				mkdir($tmpdir);
			}

			$cmd = '';

			foreach($files as &$file) {
				echo str_pad($file, 40) . "[prepare]\n";

				$tmpfile = $tmpdir . pathinfo($file, PATHINFO_BASENAME);

				$cmd .= '--js ' . escapeshellarg($tmpfile) . ' ';

				$output = system(dirname(__FILE__) . DIRECTORY_SEPARATOR . 
					'jsprepare ' . escapeshellarg(PATH_PUBLIC . $file) . ' > ' . 
					escapeshellarg($tmpfile));
			}

			$filecut = pathinfo($filename, PATHINFO_FILENAME) . ($inc < 1 ? '' : ($inc + 1)) . '.js';
			$fileout = $outdir . 'js' . DIRECTORY_SEPARATOR . $filecut;

			if (!file_exists(dirname($fileout))) {
				mkdir(dirname($fileout));
			}

			$cmd = 'java -jar ' . escapeshellarg($path_gcc) . ' ' . $cmd;

			foreach(array('jquery', 'json', 'localStorage', 'console') as $ext) {
				$cmd .= ' --externs ' . escapeshellarg(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'externs' . DIRECTORY_SEPARATOR . $ext . '.js');
			}

			$cmd .= ' --compilation_level ADVANCED_OPTIMIZATIONS --warning_level VERBOSE > ' . escapeshellarg($fileout);

			echo "\n" . str_pad('js block #' . ($inc + 1), 40) . "[compiling]\n";

			$output = system($cmd);

			system('gzip -c9 ' . escapeshellarg($fileout) . ' > ' . escapeshellarg($fileout . '.gz'));

			// cleanup
			foreach(glob($tmpdir . '/*') as $file) {
				unlink($file);
			}

			rmdir($tmpdir);

			if ('' !== $output) {
				echo "!!! Error compiling javascript !!!\n";
				die($output . "\n");
			}
		}

		echo "\n";

		$content = str_replace($src[$bkey], '<script language="javascript" src="/js/' . $filecut . '?' . $dd . '"></script>', $content);
	}
}

// compressing content

$content = preg_replace('/<!--(.*?)!-->/siu', '', $content);
$content = Page::compress($content);

// and save
file_put_contents($outdir . pathinfo($filename, PATHINFO_BASENAME), $content);
